name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build:
    permissions:
        contents: read
        pages: write  
        id-token: write 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build:css 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./out
                
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ github.token }}
